#### 웹 크롤링
1. 사용할 라이브러리 목록
    - requests
        - 웹 통신을 위한 라이브러리
        - 웹 서버에 요청을보내고 응답을 받아오는 라이브러리
        - get( 웹주소, prams = data, header = data )
    - bs4
        - BeautifulSoup class를 사용
        - html문서형 데이터를 parsing을 하여 데이터를 쉽게 추출할수 있도록 도와주는 기능
        - html의 TAG를 기준으로 데이터를 추출
        - 웹의 구조를 어느정도 인지하고 사용하면 쉽게 접근이 가능
        - Parser를 활용해서 python에서 접근이 쉽게 객체형태로 제공
    - selenium
        - 웹 어플리케이션을 테스트를 하기 위한 라이브러리
        - 웹 브라우저를 python이 code를 이용해서 제어
        - Chrome의 버전이 구버전이거나 selenium이 구 버전인 경우에는 별도의 소프트웨어를 설치
        - 특정 동적인 웹 페이지에서 데이터를 가지고 올때 사용

In [1]:
import requests
from bs4 import BeautifulSoup as bs

In [2]:
url = "http://www.naver.com"
response = requests.get(url)

In [3]:
response

In [4]:
html_data = response.text

In [5]:
type(html_data)

str

In [6]:
html_data.find('네이버')

378

In [7]:
html_data[378:410]

'네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요'

In [8]:
# parsing 작업 ; 데이터의 타입을 변경 ( 내가 사용하기 편한 형태로 변경 )
soup = bs(html_data, 'html.parser')

In [9]:
type(soup)

bs4.BeautifulSoup

- BeautifulSoup 내장함수
    - soup.태그명 -> html 문서에서 해당 태그명의 첫번째 정보를 출력
    - soup.태그명.string -> 첫번째 정보에서 contents부분의 문자를 출력
    - soup.태그명['속성명'] : 첫번째 태그의 정보에서 속성의 값을 출력
    - find(태그명)
        - html 문서에서 해당 태그명의 첫번째 정보를 출력
        - find(속성명 = 속성값) : 태그들 중 해당 속성을 가지고 속성값을 가진 태그의 첫번째 정보를 출력
        - 반환되는 값의 type은 TAG
    - find_all(태그명)
        - html 문서에서 해당 태그명의 모든 정보를 출력
        - limit 매개변수 : 태그 정보의 개수를 설정
        - 반환되는 값의 type이 TAG_list

In [10]:
# soup에서 a태그의 정보를 출력
print(soup.a)

<a href="#topAsideButton"><span>상단영역 바로가기</span></a>

In [11]:
print(soup.find('a'))

<a href="#topAsideButton"><span>상단영역 바로가기</span></a>

In [12]:
print(soup.a.string)

상단영역 바로가기

In [13]:
print(soup.a['href'])

#topAsideButton

In [14]:
type(soup.a)

bs4.element.Tag

In [15]:
type(soup.find('a'))

bs4.element.Tag

In [16]:
type(soup.find_all('a'))

bs4.element.ResultSet

In [17]:
# a_list = soup.find_all('a', limit=3)
a_list = soup.find_all('a')

In [18]:
a_list

[<a href="#topAsideButton"><span>상단영역 바로가기</span></a>,
 <a href="#shortcutArea"><span>서비스 메뉴 바로가기</span></a>,
 <a href="#newsstand"><span>새소식 블록 바로가기</span></a>,
 <a href="#shopping"><span>쇼핑 블록 바로가기</span></a>,
 <a href="#feed"><span>관심사 블록 바로가기</span></a>,
 <a href="#account"><span>MY 영역 바로가기</span></a>,
 <a href="#widgetboard"><span>위젯 보드 바로가기</span></a>,
 <a href="#viewSetting"><span>보기 설정 바로가기</span></a>]

In [19]:
a_list[1].find('span')

In [20]:
# a_list에 있는 모든 원소들에 contents만 추출하여 새로운 리스트 생성

# case1 반복문 이용
contents_list = []

# 반복문 생성
for a_tag in a_list:
    # a_tag -> a_list에 있는 각 원소(TAG)들이 한번씩 대입
    contents_list.append( a_tag.string )

contents_list

['상단영역 바로가기',
 '서비스 메뉴 바로가기',
 '새소식 블록 바로가기',
 '쇼핑 블록 바로가기',
 '관심사 블록 바로가기',
 'MY 영역 바로가기',
 '위젯 보드 바로가기',
 '보기 설정 바로가기']

In [21]:
# while문
contents_list2 = []

# 초기값
i = 0

while True:
    try:
        contents_list2.append(a_list[i].get_text())
        i += 1
    except:
        break
contents_list2

['상단영역 바로가기',
 '서비스 메뉴 바로가기',
 '새소식 블록 바로가기',
 '쇼핑 블록 바로가기',
 '관심사 블록 바로가기',
 'MY 영역 바로가기',
 '위젯 보드 바로가기',
 '보기 설정 바로가기']

In [22]:
# case2 map함수를 이용
list(
    map(
        lambda x : x.string,
        a_list
    )
)

['상단영역 바로가기',
 '서비스 메뉴 바로가기',
 '새소식 블록 바로가기',
 '쇼핑 블록 바로가기',
 '관심사 블록 바로가기',
 'MY 영역 바로가기',
 '위젯 보드 바로가기',
 '보기 설정 바로가기']

In [23]:
def get_string(x):
    # x에는 TAG 데이터 대입
    result = x.get_text()
    return result

list(
    map(
        get_string,
        a_list
    )
)

['상단영역 바로가기',
 '서비스 메뉴 바로가기',
 '새소식 블록 바로가기',
 '쇼핑 블록 바로가기',
 '관심사 블록 바로가기',
 'MY 영역 바로가기',
 '위젯 보드 바로가기',
 '보기 설정 바로가기']

In [24]:
# 네이버 파이낸스
# 1. 요청을 보내고 응답을 받는다.
url = "https://finance.naver.com/"
response = requests.get(url)

In [25]:
response

In [26]:
# 2. 응답 메시지에서 문자로 출력변수에 저장
html_data = response.text

In [27]:
# bs4에 BeautifulSoup을 이용하여 데이터를 피싱 (class 생성)
soup = bs(html_data, 'html.parser')

In [28]:
# 주요뉴스의 헤드라인 텍스트를 출력
# div TAG들 중에 class 속성의 값이 "section_strategy"인 태그를 찾는다.

len(soup.find_all('div', attrs={
    'class' : 'section_strategy'
}))
# find_all로 태그를 검색하고 길이를 확인하니 1
# html 문서에서 해당 태그는 1개 -> find()함수를 이용

1

In [29]:
div_data = soup.find('div', attrs={
    'class' : 'section_strategy'
})

In [30]:
# div_data에서 li태그의 정보를 출력
li_list = div_data.find_all('li')

In [31]:
# li_list에서 텍스트를 추출하여 새로운 리스트로 생성
news_data = list(
    map(
        lambda x : x.get_text().strip(),
        li_list
    )
)

In [32]:
news_data

['"땡큐, 트럼프"…관세 여파로 가격 ↑, 철강·알류미늄株 급등 [줍줍리포트]',
 '“미장에서 국장으로 환승”… 韓 증시 ETF 담은 개미들',
 '너도나도 감액배당…“과세 개편은 신중” [마켓딥다이브]',
 '휴젤子 소액주주연합 뿔났다 “정부 밸류업 정책과 엇박자 ”[fn마켓워치]',
 '"휴지조각 될라"…금감원 찾은 홈플러스 유동화증권 투자자들',
 '홈플러스 전단채 투자자 "상거래채권으로 인정해달라…증권사·개인 뒷통수 친 MBK"']

In [33]:
# html 문서에서 div중 class가 krx_group_type인 태그 모두를 찾는다.
divs_list = soup.find_all('div', attrs={
    'class' : 'krx_group_type'
})

In [34]:
len(divs_list)

4

In [35]:
table_data1 = divs_list[0]

In [36]:
# table 태그의 데이터를 가지고 와서 데이터프레임으로 변경
# colummns의 값을 따로 추출 (1차원 데이터)
# thead 태그 안에 th 태그들의 텍스트 추출
thead_data = table_data1.find('thead')
th_list = thead_data.find_all('th')
# th에 있는 문자를 각각 추출하여 리스트로 생성
cols = list(
    map(
        lambda x : x.get_text(),
        th_list
    )
)
cols

['종목명', '현재가', '전일대비', '등락률']

In [37]:
# values의 값을 따로 추출 (2차원 데이터)
# tbody 태그의 정보를 추출
tbody_data = table_data1.find('tbody')
# tbody_data에서 모든 tr태그를 찾는다
tr_list = tbody_data.find_all('tr')
# tr_list에서 첫번째 데이터를 추출
tr_data = tr_list[0]
# tr_data에서 th태그와 td태그를 모두 찾는다.
val_list = tr_data.find_all(['th', 'td'])
# val_list에서 텍스트를 출력하여 새로운 리스트를 생성
first_values = list(
    map(
        lambda x : x.get_text().strip(),
        val_list
    )
)
first_values

['KODEX 200선물인버스2X', '2,225', '하락 80', '-3.47%']

In [38]:
values = []
for tr_data in tr_list:
    # tr_data에서 th태그와 td태그를 모두 찾는다.
    val_list = tr_data.find_all( ['th', 'td'] )
    value = []
    for val in val_list:
        # val -> <th>..., <td>.... TAG데이터
        # val에서 텍스트를 추출하여 value에 추가
        value.append( val.get_text().strip() )
    # 두번째 반복문이 종료한 뒤 value를 values에 추가
    values.append(value)
values

[['KODEX 200선물인버스2X', '2,225', '하락 80', '-3.47%'],
 ['삼성중공업', '14,370', '상승 150', '+1.05%'],
 ['티에스넥스젠', '243', '상승 37', '+17.96%'],
 ['인콘', '289', '상승 37', '+14.68%'],
 ['KODEX 코스닥150선물인버스', '3,850', '하락 30', '-0.77%'],
 ['동양철관', '901', '하락 40', '-4.25%'],
 ['KODEX 레버리지', '15,840', '상승 490', '+3.19%'],
 ['KODEX 코스닥150레버리지', '7,645', '상승 120', '+1.59%'],
 ['우듬지팜', '1,553', '상승 82', '+5.57%'],
 ['삼성전자', '55,200', '상승 1,600', '+2.99%'],
 ['KODEX 인버스', '4,480', '하락 80', '-1.75%'],
 ['티로보틱스', '14,390', '상승 1,970', '+15.86%'],
 ['에스엠씨지', '4,085', '상승 940', '+29.89%'],
 ['케이바이오', '239', '상승 13', '+5.75%'],
 ['아이씨티케이', '12,510', '상승 1,090', '+9.54%']]

In [39]:
def func_1(tr_data):
    # x 매개변수에 대입이 될 데이터? -> tr_list에 각 원소들이 대입
    val_list = tr_data.find_all( ['th', 'td'] )
    result = list(
        map(
            lambda val : val.get_text().strip(),
            val_list
        )
    )
    return result

values2 = list(
    map(
    func_1,
    tr_list
    )
)
values2

[['KODEX 200선물인버스2X', '2,225', '하락 80', '-3.47%'],
 ['삼성중공업', '14,370', '상승 150', '+1.05%'],
 ['티에스넥스젠', '243', '상승 37', '+17.96%'],
 ['인콘', '289', '상승 37', '+14.68%'],
 ['KODEX 코스닥150선물인버스', '3,850', '하락 30', '-0.77%'],
 ['동양철관', '901', '하락 40', '-4.25%'],
 ['KODEX 레버리지', '15,840', '상승 490', '+3.19%'],
 ['KODEX 코스닥150레버리지', '7,645', '상승 120', '+1.59%'],
 ['우듬지팜', '1,553', '상승 82', '+5.57%'],
 ['삼성전자', '55,200', '상승 1,600', '+2.99%'],
 ['KODEX 인버스', '4,480', '하락 80', '-1.75%'],
 ['티로보틱스', '14,390', '상승 1,970', '+15.86%'],
 ['에스엠씨지', '4,085', '상승 940', '+29.89%'],
 ['케이바이오', '239', '상승 13', '+5.75%'],
 ['아이씨티케이', '12,510', '상승 1,090', '+9.54%']]

In [40]:
import pandas as pd

In [41]:
# cols, values를 이용하여 데이터프레임을 생성 
df = pd.DataFrame(values, columns=cols)
df

                  종목명     현재가      전일대비      등락률
0    KODEX 200선물인버스2X   2,225     하락 80   -3.47%
1               삼성중공업  14,370    상승 150   +1.05%
2              티에스넥스젠     243     상승 37  +17.96%
3                  인콘     289     상승 37  +14.68%
4   KODEX 코스닥150선물인버스   3,850     하락 30   -0.77%
5                동양철관     901     하락 40   -4.25%
6          KODEX 레버리지  15,840    상승 490   +3.19%
7    KODEX 코스닥150레버리지   7,645    상승 120   +1.59%
8                우듬지팜   1,553     상승 82   +5.57%
9                삼성전자  55,200  상승 1,600   +2.99%
10          KODEX 인버스   4,480     하락 80   -1.75%
11              티로보틱스  14,390  상승 1,970  +15.86%
12              에스엠씨지   4,085    상승 940  +29.89%
13              케이바이오     239     상승 13   +5.75%
14             아이씨티케이  12,510  상승 1,090   +9.54%

In [42]:
# divs_list의 데이터들을 한번씩 데이터프레임으로 변환
num = 1
for table_data in divs_list:
    # 컬럼의 데이터를 생성하는 부분
    thead_data = table_data.find('thead')
    th_list = thead_data.find_all('th')
    # th에 있는 문자를 각각 추출하여 리스트로 생성
    cols = list(
        map(
            lambda x : x.get_text(),
            th_list
        )
    )
    # values를 생성하는 부분
    tbody_data = table_data.find('tbody')
    # tbody_data에서 모든 tr태그를 찾는다
    tr_list = tbody_data.find_all('tr')

    values = []
    for tr_data in tr_list:
        # tr_data에서 th태그와 td태그를 모두 찾는다.
        val_list = tr_data.find_all( ['th', 'td'] )
        value = []
        for val in val_list:
            # val -> <th>..., <td>.... TAG데이터
            # val에서 텍스트를 추출하여 value에 추가
            value.append( val.get_text().strip() )
        # 두번째 반복문이 종료한 뒤 value를 values에 추가
        values.append(value)

    globals()[f"df{num}"] = pd.DataFrame(values, columns=cols)
    num += 1

In [43]:
df1

                  종목명     현재가      전일대비      등락률
0    KODEX 200선물인버스2X   2,225     하락 80   -3.47%
1               삼성중공업  14,370    상승 150   +1.05%
2              티에스넥스젠     243     상승 37  +17.96%
3                  인콘     289     상승 37  +14.68%
4   KODEX 코스닥150선물인버스   3,850     하락 30   -0.77%
5                동양철관     901     하락 40   -4.25%
6          KODEX 레버리지  15,840    상승 490   +3.19%
7    KODEX 코스닥150레버리지   7,645    상승 120   +1.59%
8                우듬지팜   1,553     상승 82   +5.57%
9                삼성전자  55,200  상승 1,600   +2.99%
10          KODEX 인버스   4,480     하락 80   -1.75%
11              티로보틱스  14,390  상승 1,970  +15.86%
12              에스엠씨지   4,085    상승 940  +29.89%
13              케이바이오     239     상승 13   +5.75%
14             아이씨티케이  12,510  상승 1,090   +9.54%

In [44]:
df2

         종목명      현재가        전일대비      등락률
0    쓰리에이로직스    9,510   상한가 2,190  +29.92%
1      에스엠씨지    4,085     상한가 940  +29.89%
2      클리노믹스      592     상한가 136  +29.82%
3     참엔지니어링      305      상한가 70  +29.79%
4       아센디오    2,695      상승 610  +29.26%
5   씨앤씨인터내셔널   41,925    상승 9,075  +27.63%
6      파인메딕스   11,350    상승 2,150  +23.37%
7      그린리소스   17,610    상승 3,040  +20.86%
8      레이저옵텍   10,060    상승 1,730  +20.77%
9    퀄리타스반도체   17,080    상승 2,860  +20.11%
10    티에스넥스젠      243       상승 37  +17.96%
11      풍원정밀   13,130    상승 1,980  +17.76%
12      고려아연  994,000  상승 149,000  +17.63%
13     티로보틱스   14,390    상승 1,970  +15.86%
14        인콘      289       상승 37  +14.68%

In [45]:
df3

                      종목명      현재가        전일대비      등락률
0                  더테크놀로지      589     하락 -251  -29.88%
1                     오비고    5,120     하락 -750  -12.78%
2                  카이노스메드    1,254     하락 -162  -11.44%
3                  LIG넥스원  277,500  하락 -31,500  -10.19%
4                      한화   45,850   하락 -5,150  -10.10%
5               디에이치엑스컴퍼니      891      하락 -99  -10.00%
6                  엠앤씨솔루션   77,600   하락 -8,500   -9.87%
7                     넥스틸   15,480   하락 -1,540   -9.05%
8                   한성크린텍    1,339     하락 -126   -8.60%
9                    성우전자    2,335     하락 -215   -8.43%
10                   한화오션   71,600   하락 -6,400   -8.21%
11                  HJ중공업    7,890     하락 -660   -7.72%
12                  한화시스템   35,100   하락 -2,900   -7.63%
13  한투 레버리지 천연가스 선물 ETN B   13,020   하락 -1,065   -7.56%
14                 오리엔트정공    7,190     하락 -560   -7.23%

In [46]:
df4

          종목명        현재가       전일대비     등락률
0        삼성전자     55,200   상승 1,600  +2.99%
1      SK하이닉스    199,150  상승 11,350  +6.04%
2    LG에너지솔루션    347,500   상승 6,500  +1.91%
3    삼성바이오로직스  1,084,000  상승 16,000  +1.50%
4         현대차    197,700   상승 2,100  +1.07%
5        셀트리온    187,000   상승 3,600  +1.96%
6          기아     99,100     상승 700  +0.71%
7       삼성전자우     45,800     상승 800  +1.78%
8       NAVER    213,500   상승 1,000  +0.47%
9        KB금융     76,800     하락 600  -0.78%
10  한화에어로스페이스    657,000  하락 21,000  -3.10%
11    HD현대중공업    296,500   하락 1,000  -0.34%
12   POSCO홀딩스    315,500  상승 19,000  +6.41%
13      현대모비스    247,000   하락 1,000  -0.40%
14       신한지주     45,200     상승 200  +0.44%

In [47]:
df

                  종목명     현재가      전일대비      등락률
0    KODEX 200선물인버스2X   2,225     하락 80   -3.47%
1               삼성중공업  14,370    상승 150   +1.05%
2              티에스넥스젠     243     상승 37  +17.96%
3                  인콘     289     상승 37  +14.68%
4   KODEX 코스닥150선물인버스   3,850     하락 30   -0.77%
5                동양철관     901     하락 40   -4.25%
6          KODEX 레버리지  15,840    상승 490   +3.19%
7    KODEX 코스닥150레버리지   7,645    상승 120   +1.59%
8                우듬지팜   1,553     상승 82   +5.57%
9                삼성전자  55,200  상승 1,600   +2.99%
10          KODEX 인버스   4,480     하락 80   -1.75%
11              티로보틱스  14,390  상승 1,970  +15.86%
12              에스엠씨지   4,085    상승 940  +29.89%
13              케이바이오     239     상승 13   +5.75%
14             아이씨티케이  12,510  상승 1,090   +9.54%

In [48]:
pd.read_html(str(divs_list[0]))[0]

/var/folders/r7/wm80f9fd57g6h8jt36r8dgwh0000gn/T/ipykernel_20284/4072056721.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(str(divs_list[0]))[0]

                  종목명    현재가      전일대비      등락률
0    KODEX 200선물인버스2X   2225     하락 80   -3.47%
1               삼성중공업  14370    상승 150   +1.05%
2              티에스넥스젠    243     상승 37  +17.96%
3                  인콘    289     상승 37  +14.68%
4   KODEX 코스닥150선물인버스   3850     하락 30   -0.77%
5                동양철관    901     하락 40   -4.25%
6          KODEX 레버리지  15840    상승 490   +3.19%
7    KODEX 코스닥150레버리지   7645    상승 120   +1.59%
8                우듬지팜   1553     상승 82   +5.57%
9                삼성전자  55200  상승 1,600   +2.99%
10          KODEX 인버스   4480     하락 80   -1.75%
11              티로보틱스  14390  상승 1,970  +15.86%
12              에스엠씨지   4085    상승 940  +29.89%
13              케이바이오    239     상승 13   +5.75%
14             아이씨티케이  12510  상승 1,090   +9.54%

In [54]:
# KRX 상위 데이터와 NXT 상위 데이터를 모두 데이터프레임으로 생성

# div TAG중 class가 'section_sise_top'인 태그를 추출
div_data = soup.find('div', attrs={
    'class' : 'section_sise_top'
    }
)
div_data

<div class="section_sise_top">
<h2 class="h_type"><span>TOP 종목</span></h2>
<!-- KRX, NXT 탭 -->
<div class="area_tab_type">
<ul class="top_tab_list">
<!-- [D] 선택된 탭 'is_active' -->
<li class="top_tab_item top_tab_krx is_active">
<a class="top_tab_link" href="#" onclick="clickcr(this, 'top.krx', '', '', event);return false;">KRX</a>
</li>
<li class="top_tab_item top_tab_nxt">
<a class="top_tab_link" href="#" onclick="clickcr(this, 'top.nxt', '', '', event);return false;">NXT</a>
</li>
</ul>
<div class="text_nxt">
                                넥스트레이드(NXT)
                                <button class="buttton_tooltip" type="button">
<span class="icon">
<span class="blind">도움말</span>
</span>
</button>
<div class="area_tooltip">
<p>
<strong>넥스트레이드(NXT)</strong>
                                        넥스트레이드(NXT)란 대한민국
                                        최초의 대체거래소(ATS,
                                        Alternative Trading
                                        System)입니다. 아래는
                                        넥스트레이드에서 거래가 가능한
                                        종목들입니다.
                                    </p>
<span class="arrow"></span>
</div>
</div>
</div>
<!-- //KRX, NXT 탭 -->
<ul class="tab_sort_list">
<!-- [D] 선택된 탭 'is_active' -->
<li class="tab_sort_item is_active"><a class="link tab_sort_sale" href="#" onclick="clickcr(this, 'spe.sale', '', '', event);return false;"><span class="tab1"><span class="blind">거래상위</span></span></a></li>
<li class="tab_sort_item"><a class="link tab_sort_ceiling" href="#" onclick="clickcr(this, 'spe.ceiling', '', '', event);return false;"><span class="tab2"><span class="blind">상승</span></span></a></li>
<li class="tab_sort_item"><a class="link tab_sort_bottom" href="#" onclick="clickcr(this, 'spe.bottom', '', '', event);return false;"><span class="tab3"><span class="blind">하락</span></span></a></li>
<li class="tab_sort_item"><a class="link tab_sort_value" href="#" onclick="clickcr(this, 'spe.value', '', '', event);return false;"><span class="tab4"><span class="blind">시가총액 상위</span></span></a></li>
</ul>
<div class="group_type krx_group_type tab1 is_active">
<table class="tbl_home">
<caption>거래상위 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="_topItems1">
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>
<td>2,225</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 80</td>
<td>
<em class="down">
				-3.47%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=010140" onclick="clickcr(this, 'spe.slist', '010140', '2', event);">삼성중공업</a></th>
<td>14,370</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 150</td>
<td>
<em class="up">
				+1.05%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=043220" onclick="clickcr(this, 'spe.slist', '043220', '3', event);">티에스넥스젠</a></th>
<td>243</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 37</td>
<td>
<em class="up">
				+17.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=083640" onclick="clickcr(this, 'spe.slist', '083640', '4', event);">인콘</a></th>
<td>289</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 37</td>
<td>
<em class="up">
				+14.68%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=251340" onclick="clickcr(this, 'spe.slist', '251340', '5', event);">KODEX 코스닥150선물인버스</a></th>
<td>3,850</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 30</td>
<td>
<em class="down">
				-0.77%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=008970" onclick="clickcr(this, 'spe.slist', '008970', '6', event);">동양철관</a></th>
<td>901</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 40</td>
<td>
<em class="down">
				-4.25%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=122630" onclick="clickcr(this, 'spe.slist', '122630', '7', event);">KODEX 레버리지</a></th>
<td>15,840</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 490</td>
<td>
<em class="up">
				+3.19%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=233740" onclick="clickcr(this, 'spe.slist', '233740', '8', event);">KODEX 코스닥150레버리지</a></th>
<td>7,645</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 120</td>
<td>
<em class="up">
				+1.59%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=403490" onclick="clickcr(this, 'spe.slist', '403490', '9', event);">우듬지팜</a></th>
<td>1,553</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 82</td>
<td>
<em class="up">
				+5.57%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=005930" onclick="clickcr(this, 'spe.slist', '005930', '10', event);">삼성전자</a></th>
<td>55,200</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,600</td>
<td>
<em class="up">
				+2.99%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=114800" onclick="clickcr(this, 'spe.slist', '114800', '11', event);">KODEX 인버스</a></th>
<td>4,480</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 80</td>
<td>
<em class="down">
				-1.75%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=117730" onclick="clickcr(this, 'spe.slist', '117730', '12', event);">티로보틱스</a></th>
<td>14,390</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,970</td>
<td>
<em class="up">
				+15.86%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=460870" onclick="clickcr(this, 'spe.slist', '460870', '13', event);">에스엠씨지</a></th>
<td>4,085</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 940</td>
<td>
<em class="up">
				+29.89%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=038530" onclick="clickcr(this, 'spe.slist', '038530', '14', event);">케이바이오</a></th>
<td>239</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 13</td>
<td>
<em class="up">
				+5.75%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=456010" onclick="clickcr(this, 'spe.slist', '456010', '15', event);">아이씨티케이</a></th>
<td>12,510</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,090</td>
<td>
<em class="up">
				+9.54%
				</em>
</td>
</tr>
</tbody>
</table>
<a class="btn_more" href="/sise/sise_quant.naver" onclick="clickcr(this, 'spe.more', '', '', event);"><em class="btn_more4"><span class="blind">거래상위 더보기</span></em></a>
</div>
<div class="group_type nxt_group_type tab1 is_active" style="display:none">
<table class="tbl_home">
<caption>거래상위 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="nxt_topItems1">
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=086450" onclick="clickcr(this, 'spe.slist', '086450', '1', event);">동국제약</a></th>
<td>15,220</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 90</td>
<td>
<em class="down">
				-0.59%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=032640" onclick="clickcr(this, 'spe.slist', '032640', '2', event);">LG유플러스</a></th>
<td>10,660</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 210</td>
<td>
<em class="up">
				+2.01%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=122870" onclick="clickcr(this, 'spe.slist', '122870', '3', event);">와이지엔터테인먼트</a></th>
<td>62,400</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,100</td>
<td>
<em class="up">
				+1.79%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=010950" onclick="clickcr(this, 'spe.slist', '010950', '4', event);">S-Oil</a></th>
<td>60,500</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 300</td>
<td>
<em class="up">
				+0.50%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=030000" onclick="clickcr(this, 'spe.slist', '030000', '5', event);">제일기획</a></th>
<td>17,290</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 130</td>
<td>
<em class="down">
				-0.75%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=120110" onclick="clickcr(this, 'spe.slist', '120110', '6', event);">코오롱인더</a></th>
<td>32,100</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 300</td>
<td>
<em class="down">
				-0.93%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=056190" onclick="clickcr(this, 'spe.slist', '056190', '7', event);">에스에프에이</a></th>
<td>19,530</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 30</td>
<td>
<em class="down">
				-0.15%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078340" onclick="clickcr(this, 'spe.slist', '078340', '8', event);">컴투스</a></th>
<td>43,050</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,300</td>
<td>
<em class="up">
				+3.11%
				</em>
</td>
</tr>
<tr class="same">
<th scope="row"><a href="/item/main.naver?code=023530" onclick="clickcr(this, 'spe.slist', '023530', '9', event);">롯데쇼핑</a></th>
<td>67,500</td>
<td><em class="bu_p bu_pn"><span class="blind">보합</span></em></td>
<td>
<em class="steady">
				0.00%
				</em>
</td>
</tr>
<tr class="same">
<th scope="row"><a href="/item/main.naver?code=215000" onclick="clickcr(this, 'spe.slist', '215000', '10', event);">골프존</a></th>
<td>59,700</td>
<td><em class="bu_p bu_pn"><span class="blind">보합</span></em></td>
<td>
<em class="steady">
				0.00%
				</em>
</td>
</tr>
</tbody>
</table>
<a class="btn_more" href="/sise/nxt_sise_quant.naver" onclick="clickcr(this, 'spe.more', '', '', event);"><em class="btn_more4"><span class="blind">거래상위 더보기</span></em></a>
</div>
<div class="group_type krx_group_type tab2">
<table class="tbl_home">
<caption>상승 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="_topItems2">
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=177900" onclick="clickcr(this, 'spe.clist', '177900', '1', event);">쓰리에이로직스</a></th>
<td>9,510</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 2,190 </td>
<td>
<em class="up">
				+29.92%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=460870" onclick="clickcr(this, 'spe.clist', '460870', '2', event);">에스엠씨지</a></th>
<td>4,085</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 940 </td>
<td>
<em class="up">
				+29.89%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=352770" onclick="clickcr(this, 'spe.clist', '352770', '3', event);">클리노믹스</a></th>
<td>592</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 136 </td>
<td>
<em class="up">
				+29.82%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=009310" onclick="clickcr(this, 'spe.clist', '009310', '4', event);">참엔지니어링</a></th>
<td>305</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 70 </td>
<td>
<em class="up">
				+29.79%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=012170" onclick="clickcr(this, 'spe.clist', '012170', '5', event);">아센디오</a></th>
<td>2,695</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 610 </td>
<td>
<em class="up">
				+29.26%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=352480" onclick="clickcr(this, 'spe.clist', '352480', '6', event);">씨앤씨인터내셔널</a></th>
<td>41,925</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 9,075 </td>
<td>
<em class="up">
				+27.63%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=387570" onclick="clickcr(this, 'spe.clist', '387570', '7', event);">파인메딕스</a></th>
<td>11,350</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,150 </td>
<td>
<em class="up">
				+23.37%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=402490" onclick="clickcr(this, 'spe.clist', '402490', '8', event);">그린리소스</a></th>
<td>17,610</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,040 </td>
<td>
<em class="up">
				+20.86%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=199550" onclick="clickcr(this, 'spe.clist', '199550', '9', event);">레이저옵텍</a></th>
<td>10,060</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,730 </td>
<td>
<em class="up">
				+20.77%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=432720" onclick="clickcr(this, 'spe.clist', '432720', '10', event);">퀄리타스반도체</a></th>
<td>17,080</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,860 </td>
<td>
<em class="up">
				+20.11%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=043220" onclick="clickcr(this, 'spe.clist', '043220', '11', event);">티에스넥스젠</a></th>
<td>243</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 37 </td>
<td>
<em class="up">
				+17.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=371950" onclick="clickcr(this, 'spe.clist', '371950', '12', event);">풍원정밀</a></th>
<td>13,130</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,980 </td>
<td>
<em class="up">
				+17.76%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=010130" onclick="clickcr(this, 'spe.clist', '010130', '13', event);">고려아연</a></th>
<td>994,000</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 149,000 </td>
<td>
<em class="up">
				+17.63%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=117730" onclick="clickcr(this, 'spe.clist', '117730', '14', event);">티로보틱스</a></th>
<td>14,390</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,970 </td>
<td>
<em class="up">
				+15.86%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=083640" onclick="clickcr(this, 'spe.clist', '083640', '15', event);">인콘</a></th>
<td>289</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 37 </td>
<td>
<em class="up">
				+14.68%
				</em>
</td>
</tr>
</tbody>
</table>
<a class="btn_more" href="/sise/sise_rise.naver" onclick="clickcr(this, 'spe.more', '', '', event);"><em class="btn_more4"><span class="blind">상승 더보기</span></em></a>
</div>
<div class="group_type nxt_group_type tab2" style="display:none">
<table class="tbl_home">
<caption>상승 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="nxt_topItems2">
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078340" onclick="clickcr(this, 'spe.clist', '078340', '1', event);">컴투스</a></th>
<td>43,050</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,300 </td>
<td>
<em class="up">
				+3.11%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=032640" onclick="clickcr(this, 'spe.clist', '032640', '2', event);">LG유플러스</a></th>
<td>10,660</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 210 </td>
<td>
<em class="up">
				+2.01%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=122870" onclick="clickcr(this, 'spe.clist', '122870', '3', event);">와이지엔터테인먼트</a></th>
<td>62,400</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,100 </td>
<td>
<em class="up">
				+1.79%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=010950" onclick="clickcr(this, 'spe.clist', '010950', '4', event);">S-Oil</a></th>
<td>60,500</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 300 </td>
<td>
<em class="up">
				+0.50%
				</em>
</td>
</tr>
</tbody>
</table>
<a class="btn_more" href="/sise/nxt_sise_rise.naver" onclick="clickcr(this, 'spe.more', '', '', event);"><em class="btn_more4"><span class="blind">상승 더보기</span></em></a>
</div>
<div class="group_type krx_group_type tab3">
<table class="tbl_home">
<caption>하락 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="_topItems3">
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=043090" onclick="clickcr(this, 'spe.blist', '043090', '1', event);">더테크놀로지</a></th>
<td>589</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> -251</td>
<td>
<em class="down">
				-29.88%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=352910" onclick="clickcr(this, 'spe.blist', '352910', '2', event);">오비고</a></th>
<td>5,120</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> -750</td>
<td>
<em class="down">
				-12.78%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=284620" onclick="clickcr(this, 'spe.blist', '284620', '3', event);">카이노스메드</a></th>
<td>1,254</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> -162</td>
<td>
<em class="down">
				-11.44%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=079550" onclick="clickcr(this, 'spe.blist', '079550', '4', event);">LIG넥스원</a></th>
<td>277,500</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> -31,500</td>
<td>
<em class="down">
				-10.19%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=000880" onclick="clickcr(this, 'spe.blist', '000880', '5', event);">한화</a></th>
<td>45,850</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> -5,150</td>
<td>
<em class="down">
				-10.10%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=031860" onclick="clickcr(this, 'spe.blist', '031860', '6', event);">디에이치엑스컴퍼니</a></th>
<td>891</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> -99</td>
<td>
<em class="down">
				-10.00%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=484870" onclick="clickcr(this, 'spe.blist', '484870', '7', event);">엠앤씨솔루션</a></th>
<td>77,600</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> -8,500</td>
<td>
<em class="down">
				-9.87%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=092790" onclick="clickcr(this, 'spe.blist', '092790', '8', event);">넥스틸</a></th>
<td>15,480</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> -1,540</td>
<td>
<em class="down">
				-9.05%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=066980" onclick="clickcr(this, 'spe.blist', '066980', '9', event);">한성크린텍</a></th>
<td>1,339</td>

In [56]:
# pandas에 내장된 read_html()함수를 이용하여 div_data의 테이블 태그를 모두 데이터프레임으로 변환
# div_data를 문자로 변경
div_data = str(div_data)

dfs = pd.read_html(div_data)

/var/folders/r7/wm80f9fd57g6h8jt36r8dgwh0000gn/T/ipykernel_20284/586543590.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(div_data)

In [ ]:
# html5lib 에러 나는 경우
# !pip install html5lib

Requirement already satisfied: html5lib in /opt/anaconda3/lib/python3.9/site-packages (1.1)
Requirement already satisfied: webencodings in /opt/anaconda3/lib/python3.9/site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in /opt/anaconda3/lib/python3.9/site-packages (from html5lib) (1.16.0)

In [58]:
len(dfs)

8

In [59]:
# 홀수 위치의 데이터는 krx1, krx2, krx3, krx4 전역변수에 각각 대입

# 짝수 위치의 데이터는 nxt1, nxt2, nxt3, nxt4 전역변수에 각각 대입
# 조건식 : 홀수의 조건식? -> 2로 나누었을때 나머지 1인 경우

for i in range(len(dfs)):
    # print(i)
    # i가 0인 경우 krx1변수 생성 dfs[0]대입
    # i가 1인 경우 krx2변수 생성 dfs[1]대입
    num = i // 2 + 1
    if (i % 2 == 0):
        globals()[f"krx{num}"] = dfs[i]
    else:
        globals()[f"nxt{num}"] = dfs[i]

In [63]:
nxt4

         종목명    현재가      전일대비     등락률
0      S-Oil  60500    상승 300  +0.50%
1     LG유플러스  10660    상승 210  +2.01%
2       제일기획  17290    하락 130  -0.75%
3       롯데쇼핑  67500        보합   0.00%
4  와이지엔터테인먼트  62400  상승 1,100  +1.79%
5      코오롱인더  32100    하락 300  -0.93%
6     에스에프에이  19530     하락 30  -0.15%
7       동국제약  15220     하락 90  -0.59%
8        컴투스  43050  상승 1,300  +3.11%
9        골프존  59700        보합   0.00%